import java.awt.Color;
import java.sql.*;
import javax.swing.ComboBoxModel;
import javax.swing.JFrame;
import net.proteanit.sql.DbUtils;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Owner
 */
public class DBControls extends javax.swing.JFrame {

    Connection c=null;
    /**
     * Creates new form DBControls
     */
    public DBControls() {
        initComponents();
        this.setVisible(true);
        this.getContentPane().setBackground(Color.WHITE);
        this.setTitle("Manage");
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        try{
            Class.forName("com.mysql.jdbc.Driver");
            c=DriverManager.getConnection("jdbc:mysql://localhost/informationkiosk","root",null);
            PreparedStatement p=c.prepareCall("select concat(MonthName(`Day`),' ',dayofmonth(`Day`),', ',year(`day`),'=>',Activity) as `Date` from Calendar order by `day`");
            ResultSet r=p.executeQuery();
            while(r.next()){
                String s=r.getString("Date");
                this.chData.add(s);
            }
        }
        catch(Exception e){
            javax.swing.JOptionPane.showMessageDialog(null,"Fail due to "+e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JLabel();
        lblAdminControls = new javax.swing.JLabel();
        lblFurtherInstructions = new javax.swing.JLabel();
        pnlAddOrUpdate = new javax.swing.JPanel();
        txtDate = new javax.swing.JTextField();
        lblDate = new javax.swing.JLabel();
        btnAddOrUpdate = new javax.swing.JButton();
        txtActivity = new javax.swing.JTextField();
        lblActivity = new javax.swing.JLabel();
        pnlDataRemoval = new javax.swing.JPanel();
        btnDelete = new javax.swing.JButton();
        lblActivity1 = new javax.swing.JLabel();
        btnClearDB = new javax.swing.JButton();
        chData = new java.awt.Choice();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/backbtn.png"))); // NOI18N
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
        });

        lblAdminControls.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        lblAdminControls.setForeground(new java.awt.Color(102, 0, 0));
        lblAdminControls.setText("Admin Control Center");

        lblFurtherInstructions.setForeground(new java.awt.Color(102, 0, 0));
        lblFurtherInstructions.setText("After modifying data, please click back button to Log-out");

        pnlAddOrUpdate.setBackground(new java.awt.Color(255, 255, 255));
        pnlAddOrUpdate.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 0)), "Adding and Changing Data", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(102, 0, 0)));

        lblDate.setForeground(new java.awt.Color(102, 0, 0));
        lblDate.setText("Date(yyyy-mm-dd):");

        btnAddOrUpdate.setForeground(new java.awt.Color(102, 0, 0));
        btnAddOrUpdate.setText("Add/Update");
        btnAddOrUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddOrUpdateActionPerformed(evt);
            }
        });

        lblActivity.setForeground(new java.awt.Color(102, 0, 0));
        lblActivity.setText("Activity:");

        javax.swing.GroupLayout pnlAddOrUpdateLayout = new javax.swing.GroupLayout(pnlAddOrUpdate);
        pnlAddOrUpdate.setLayout(pnlAddOrUpdateLayout);
        pnlAddOrUpdateLayout.setHorizontalGroup(
            pnlAddOrUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAddOrUpdateLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlAddOrUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDate)
                    .addComponent(lblActivity))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAddOrUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtActivity, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddOrUpdate))
                .addContainerGap())
        );
        pnlAddOrUpdateLayout.setVerticalGroup(
            pnlAddOrUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAddOrUpdateLayout.createSequentialGroup()
                .addGap(0, 25, Short.MAX_VALUE)
                .addGroup(pnlAddOrUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAddOrUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtActivity, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblActivity))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddOrUpdate))
        );

        pnlDataRemoval.setBackground(new java.awt.Color(255, 255, 255));
        pnlDataRemoval.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 0)), "Data Removal", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(102, 0, 0)));

        btnDelete.setForeground(new java.awt.Color(102, 0, 0));
        btnDelete.setText("Remove");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        lblActivity1.setForeground(new java.awt.Color(102, 0, 0));
        lblActivity1.setText("Activity to Remove:");

        btnClearDB.setForeground(new java.awt.Color(102, 0, 0));
        btnClearDB.setText("Clear Database");
        btnClearDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearDBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDataRemovalLayout = new javax.swing.GroupLayout(pnlDataRemoval);
        pnlDataRemoval.setLayout(pnlDataRemovalLayout);
        pnlDataRemovalLayout.setHorizontalGroup(
            pnlDataRemovalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDataRemovalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblActivity1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDataRemovalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnClearDB)
                    .addGroup(pnlDataRemovalLayout.createSequentialGroup()
                        .addComponent(chData, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(btnDelete)))
                .addGap(18, 18, 18))
        );
        pnlDataRemovalLayout.setVerticalGroup(
            pnlDataRemovalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDataRemovalLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pnlDataRemovalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlDataRemovalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnDelete, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblActivity1))
                    .addComponent(chData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClearDB)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFurtherInstructions)
                            .addComponent(lblAdminControls)))
                    .addComponent(pnlAddOrUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlDataRemoval, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack)
                    .addComponent(lblAdminControls))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFurtherInstructions)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlAddOrUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlDataRemoval, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        new Welcome();
        this.dispose();
    }//GEN-LAST:event_btnBackMouseClicked

    private void btnAddOrUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddOrUpdateActionPerformed
        try{
            PreparedStatement p=c.prepareCall("Insert into calendar values('"+this.txtDate.getText()+"','"+this.txtActivity.getText()+"');");
            p.execute();
            javax.swing.JOptionPane.showMessageDialog(null,"Data Successfully Added");
            new DBControls();
            this.dispose();
            return;
        }
        catch(Exception e){
        }
        try{
            PreparedStatement p=c.prepareCall("update calendar set `day`='"+this.txtDate.getText()+"',Activity='"+this.txtActivity.getText()+"' where `day`='"+this.txtDate.getText()+"' or `Activity`='"+this.txtActivity.getText()+"'");
            p.executeUpdate();
            javax.swing.JOptionPane.showMessageDialog(null,"Data Successfully Edited");
            new DBControls();
            this.dispose();
            return;
        }
        catch(Exception e){
           javax.swing.JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_btnAddOrUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try{
            PreparedStatement p=c.prepareCall("Delete from calendar where Activity='"+this.chData.getSelectedItem().substring(chData.getSelectedItem().lastIndexOf("=>")+2,this.chData.getSelectedItem().length())+"';");
            p.execute();
            javax.swing.JOptionPane.showMessageDialog(null,"Data Successfully Deleted");
        }
        catch(Exception e){
        }
        new DBControls();
        this.dispose();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearDBActionPerformed
        try{
            PreparedStatement p=c.prepareCall("Delete from calendar;");
            p.execute();
            javax.swing.JOptionPane.showMessageDialog(null,"Data Successfully Deleted");
        }
        catch(Exception e){
        }
        new DBControls();
        this.dispose();
    }//GEN-LAST:event_btnClearDBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DBControls.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DBControls.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DBControls.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DBControls.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DBControls().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddOrUpdate;
    private javax.swing.JLabel btnBack;
    private javax.swing.JButton btnClearDB;
    private javax.swing.JButton btnDelete;
    private java.awt.Choice chData;
    private javax.swing.JLabel lblActivity;
    private javax.swing.JLabel lblActivity1;
    private javax.swing.JLabel lblAdminControls;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblFurtherInstructions;
    private javax.swing.JPanel pnlAddOrUpdate;
    private javax.swing.JPanel pnlDataRemoval;
    private javax.swing.JTextField txtActivity;
    private javax.swing.JTextField txtDate;
    // End of variables declaration//GEN-END:variables
}
