
import java.awt.Color;
import java.awt.Graphics;
import java.io.File;
import java.util.Scanner;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Owner
 */
public class Places extends javax.swing.JFrame {
    Node []graph=new Node[82];
    /**
     * Creates new form Places
     */
    public Places() {
        initComponents();
        this.setVisible(true);
        this.getContentPane().setBackground(Color.WHITE);
        this.setTitle("Places");
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        chStart.removeAll();
        chEnd.removeAll();
        String []locations={"Property Building","Printing Press Building","Laboratory High School","Pasig River","Charlie Del Rosario Hall","Student Canteen","University Canteen Sapaguita Building","Water Pump Facility","R.C. Underground Water Tank","R.C. Overhead Water Tank","NALLRC","Lagoon","Ampitheater","Physical Education Building","Tahanan ng Alumni","Swimming Pool","Mabini Monument PUP Obelisk","Freedom Park","Gymnasium and Sports Center","Outdoor Basketball and Volleyball Court","Tennis Court","Covered Walkway","Anonas Street","Visitor Information Center","Pylon","Railroad Track","Teresa Street","Main Gate Mural Bass Sculpture","Guard House","Covered Walkway","Gazebo","Apolinario  Mabini Shrine","Freedom Park","Grandstand","Track and Football Oval","Community Building(Gabriela Silang)","Flag Pole","Apolinario Mabini Shrine","Interfaith Chapel","North Wing","Nutrition and Food Science Building","East Wing","Dome","Main Building","West Wing","South Wing","Generator Facility","PUP Sta.Mesa Ferry Station","Campus Development and Maintenance Building"};
        for(int x=0;x<locations.length;x++){
            this.chStart.add(locations[x]);
            this.chEnd.add(locations[x]);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JLabel();
        imgMap = new javax.swing.JLabel();
        lblStart = new javax.swing.JLabel();
        lblEnd = new javax.swing.JLabel();
        btnOk = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        chStart = new java.awt.Choice();
        chEnd = new java.awt.Choice();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/backbtn.png"))); // NOI18N
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
        });

        imgMap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/places.png"))); // NOI18N
        imgMap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgMapMouseClicked(evt);
            }
        });

        lblStart.setForeground(new java.awt.Color(102, 0, 0));
        lblStart.setText("Start:");

        lblEnd.setForeground(new java.awt.Color(102, 0, 0));
        lblEnd.setText("End:");

        btnOk.setForeground(new java.awt.Color(102, 0, 0));
        btnOk.setText("Show Path");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Cooper Std Black", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 0));
        jLabel1.setText("Map");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(imgMap)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnOk)
                            .addComponent(lblEnd)
                            .addComponent(lblStart)
                            .addComponent(chStart, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                            .addComponent(chEnd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblStart)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(lblEnd)
                        .addGap(1, 1, 1)
                        .addComponent(chEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOk)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(imgMap)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        new Welcome();
        this.dispose();
    }//GEN-LAST:event_btnBackMouseClicked

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        Node graph[]=new Node[100];
        for(int x=0;x<this.graph.length;x++){
	graph[x] = new Node(x);
			switch (x) {
			
			case 0:	
				//property  Building
				graph[x].SetXY(69,7);
				graph[x].ArcSet.add(1);
				graph[x].ArcSet.add(2);
				graph[x].ArcSet.add(7);
				graph[x].ArcSet.add(3);  //di ko to sure kasi pasig na to. pano maglalakad diba ???
				break;

			case 1:	
				//Printing Press Building
				graph[x].SetXY(61,35);
				graph[x].ArcSet.add(0);
				graph[x].ArcSet.add(2);
				graph[x].ArcSet.add(6);
				graph[x].ArcSet.add(3);  //di ko to sure kasi pasig na to. pano maglalakad diba ???
				break;
				
			case 2:	
				//Laboratory High
				graph[x].SetXY(130, 61);
				graph[x].ArcSet.add(0);
				graph[x].ArcSet.add(1);
				break;
			
			case 3:	
				//Pasig River
				graph[x].SetXY(42, 195);
				graph[x].ArcSet.add(0);
				graph[x].ArcSet.add(1);
				graph[x].ArcSet.add(4);
				graph[x].ArcSet.add(5);
				graph[x].ArcSet.add(6);
				graph[x].ArcSet.add(41);
				graph[x].ArcSet.add(42);
				graph[x].ArcSet.add(38);
				graph[x].ArcSet.add(39);
				graph[x].ArcSet.add(40);
				graph[x].ArcSet.add(43);
				graph[x].ArcSet.add(44);
				graph[x].ArcSet.add(45);
				
				//yung sa case 3(pasig yan) di ko sure if
				//dapat pang isama kasi diba maglalakad ka sa tubig?
				
				break;
				
			case 4:	
				//Charlie Del Rosario Hall
				graph[x].SetXY(139, 133);
				graph[x].ArcSet.add(3); // to pasig river(not sure if kelangan isama)
				graph[x].ArcSet.add(5);
				graph[x].ArcSet.add(6);
				graph[x].ArcSet.add(11);
				graph[x].ArcSet.add(12);
				graph[x].ArcSet.add(36);
				graph[x].ArcSet.add(38);
				graph[x].ArcSet.add(39);
				graph[x].ArcSet.add(40);
				graph[x].ArcSet.add(41);
				graph[x].ArcSet.add(35);
				graph[x].ArcSet.add(37);
				
				break;
				
			case 5:	
				//Student Canteen
				graph[x].SetXY(149, 167);
				graph[x].ArcSet.add(3);
				graph[x].ArcSet.add(4);
				graph[x].ArcSet.add(6);
				graph[x].ArcSet.add(11);
				graph[x].ArcSet.add(12);
				graph[x].ArcSet.add(36);
				graph[x].ArcSet.add(35);
				graph[x].ArcSet.add(40);
				graph[x].ArcSet.add(39);
				graph[x].ArcSet.add(38);
				graph[x].ArcSet.add(42);
				graph[x].ArcSet.add(37);
				graph[x].ArcSet.add(45);
				
				break;
				
			case 6:	
				//University Canteen Sampaguita Building
				graph[x].SetXY(140, 186);
				graph[x].ArcSet.add(1);
				graph[x].ArcSet.add(3);
				graph[x].ArcSet.add(4);
				graph[x].ArcSet.add(5);
				graph[x].ArcSet.add(11);
				graph[x].ArcSet.add(12);
				graph[x].ArcSet.add(36);
				graph[x].ArcSet.add(40);
				graph[x].ArcSet.add(35);
				graph[x].ArcSet.add(39);
				graph[x].ArcSet.add(38);
				graph[x].ArcSet.add(41);
				graph[x].ArcSet.add(42);
				graph[x].ArcSet.add(43);
				graph[x].ArcSet.add(44);
				graph[x].ArcSet.add(32);
				break;
				
			case 7:
				//Water Pump Facility
				graph[x].SetXY(182, 6);
				graph[x].ArcSet.add(0);
				graph[x].ArcSet.add(8);
				graph[x].ArcSet.add(9);
				graph[x].ArcSet.add(10);
				graph[x].ArcSet.add(11);
				graph[x].ArcSet.add(12);
				graph[x].ArcSet.add(41);
				graph[x].ArcSet.add(42);
				graph[x].ArcSet.add(38);
				graph[x].ArcSet.add(45);
				break;
				
			case 8:
				//R.C. Underground Water Tank
				graph[x].SetXY(186, 21);
				graph[x].ArcSet.add(0);
				graph[x].ArcSet.add(7);
				graph[x].ArcSet.add(9);
				graph[x].ArcSet.add(10);
				graph[x].ArcSet.add(41);
				graph[x].ArcSet.add(38);
				graph[x].ArcSet.add(45);
				break;
				
			case 9:
				//R.C. Overheard Water Tank 
				graph[x].SetXY(192, 41);
				graph[x].ArcSet.add(7);
				graph[x].ArcSet.add(8);
				graph[x].ArcSet.add(10);
				graph[x].ArcSet.add(11);
				graph[x].ArcSet.add(41);
				graph[x].ArcSet.add(42);
				graph[x].ArcSet.add(40);
				graph[x].ArcSet.add(39);
				graph[x].ArcSet.add(38);
				graph[x].ArcSet.add(45);
				break;
				
			case 10:
				//Ninoy Aquino Library and Learning Resources Center
				graph[x].SetXY(242, 66);
				graph[x].ArcSet.add(7);
				graph[x].ArcSet.add(8);
				graph[x].ArcSet.add(9);
				graph[x].ArcSet.add(13);
				graph[x].ArcSet.add(11);
				graph[x].ArcSet.add(16);
				graph[x].ArcSet.add(30);
				graph[x].ArcSet.add(29);
				graph[x].ArcSet.add(31);
				graph[x].ArcSet.add(32);
				graph[x].ArcSet.add(33);
				graph[x].ArcSet.add(41);
				graph[x].ArcSet.add(42);
				graph[x].ArcSet.add(43);
				graph[x].ArcSet.add(44);
				
				break;
				
			case 11:
				//Lagoon
				graph[x].SetXY(258, 142);
				graph[x].ArcSet.add(10);
				graph[x].ArcSet.add(8);
				graph[x].ArcSet.add(9);
				graph[x].ArcSet.add(12);
				graph[x].ArcSet.add(13);
				graph[x].ArcSet.add(16);
				graph[x].ArcSet.add(30);
				graph[x].ArcSet.add(15);
				graph[x].ArcSet.add(19);
				graph[x].ArcSet.add(18);
				graph[x].ArcSet.add(20);
				graph[x].ArcSet.add(17);
				graph[x].ArcSet.add(34);
				graph[x].ArcSet.add(29);
				graph[x].ArcSet.add(21);
				graph[x].ArcSet.add(17);
				graph[x].ArcSet.add(23);
				graph[x].ArcSet.add(24);
				graph[x].ArcSet.add(27);
				graph[x].ArcSet.add(26);
				graph[x].ArcSet.add(28);
				graph[x].ArcSet.add(31);
				graph[x].ArcSet.add(32);
				graph[x].ArcSet.add(33);
				graph[x].ArcSet.add(36);
				graph[x].ArcSet.add(35);
				graph[x].ArcSet.add(37);
				
				break;
				
			case 12:
				//Amphitheatre
				graph[x].SetXY(244, 192);
				graph[x].ArcSet.add(4);
				graph[x].ArcSet.add(5);
				graph[x].ArcSet.add(6);
				graph[x].ArcSet.add(11);
				graph[x].ArcSet.add(13);
				graph[x].ArcSet.add(14);
				graph[x].ArcSet.add(15);
				graph[x].ArcSet.add(18);
				graph[x].ArcSet.add(19);
				graph[x].ArcSet.add(20);
				graph[x].ArcSet.add(16);
				graph[x].ArcSet.add(34);
				graph[x].ArcSet.add(17);
				graph[x].ArcSet.add(30);
				graph[x].ArcSet.add(31);
				graph[x].ArcSet.add(32);
				graph[x].ArcSet.add(33);
				graph[x].ArcSet.add(36);
				graph[x].ArcSet.add(40);
				graph[x].ArcSet.add(39);
				graph[x].ArcSet.add(41);
				graph[x].ArcSet.add(42);
				graph[x].ArcSet.add(43);
				graph[x].ArcSet.add(44);
				graph[x].ArcSet.add(43);
				graph[x].ArcSet.add(45);
				graph[x].ArcSet.add(38);
				graph[x].ArcSet.add(35);
				graph[x].ArcSet.add(37);
				
				break;
				
			case 13:
				//P.E. Building
				graph[x].SetXY(311, 56);
				graph[x].ArcSet.add(10);
				graph[x].ArcSet.add(11);
				graph[x].ArcSet.add(14);
				graph[x].ArcSet.add(15);
				graph[x].ArcSet.add(19);
				graph[x].ArcSet.add(20);
				graph[x].ArcSet.add(16);
				graph[x].ArcSet.add(17);
				graph[x].ArcSet.add(30);
				graph[x].ArcSet.add(29);
				graph[x].ArcSet.add(21);
				graph[x].ArcSet.add(28);
				graph[x].ArcSet.add(32);
				graph[x].ArcSet.add(33);
				graph[x].ArcSet.add(31);
				graph[x].ArcSet.add(12);
				graph[x].ArcSet.add(34);
				graph[x].ArcSet.add(35);
				
				break;
				
			case 14:
				//Tahanan ng Alumni
				graph[x].SetXY(326, 33);
				graph[x].ArcSet.add(13);
				graph[x].ArcSet.add(15);
				graph[x].ArcSet.add(16);
				graph[x].ArcSet.add(17);
				graph[x].ArcSet.add(34);
				graph[x].ArcSet.add(35);
				graph[x].ArcSet.add(30);
				graph[x].ArcSet.add(29);
				graph[x].ArcSet.add(31);
				graph[x].ArcSet.add(32);
				graph[x].ArcSet.add(33);
				break;
				
			case 15:
				//Swimming Pool
				graph[x].SetXY(365, 40);
				graph[x].ArcSet.add(13);
				graph[x].ArcSet.add(14);
				graph[x].ArcSet.add(18);
				graph[x].ArcSet.add(19);
				graph[x].ArcSet.add(20);
				graph[x].ArcSet.add(16);
				graph[x].ArcSet.add(30);
				graph[x].ArcSet.add(29);
				graph[x].ArcSet.add(31);
				graph[x].ArcSet.add(32);
				graph[x].ArcSet.add(33);
				graph[x].ArcSet.add(17);
				graph[x].ArcSet.add(34);
				graph[x].ArcSet.add(11);
				break;
				
			case 16:
				//Mabini Monument PUP Obelisk
				graph[x].SetXY(351, 138);
				graph[x].ArcSet.add(10);
				graph[x].ArcSet.add(11);
				graph[x].ArcSet.add(13);
				graph[x].ArcSet.add(14);
				graph[x].ArcSet.add(15);
				graph[x].ArcSet.add(18);
				graph[x].ArcSet.add(19);
				graph[x].ArcSet.add(20);
				graph[x].ArcSet.add(23);
				graph[x].ArcSet.add(24);
				graph[x].ArcSet.add(27);
				graph[x].ArcSet.add(26);
				graph[x].ArcSet.add(28);
				graph[x].ArcSet.add(21);
				graph[x].ArcSet.add(29);
				graph[x].ArcSet.add(30);
				graph[x].ArcSet.add(31);
				graph[x].ArcSet.add(32);
				graph[x].ArcSet.add(33);
				graph[x].ArcSet.add(17);
				graph[x].ArcSet.add(34);
				graph[x].ArcSet.add(35);
				graph[x].ArcSet.add(37);
				graph[x].ArcSet.add(36);
				graph[x].ArcSet.add(12);
				graph[x].ArcSet.add(40);
				graph[x].ArcSet.add(39);
				graph[x].ArcSet.add(38);
				graph[x].ArcSet.add(41);
				graph[x].ArcSet.add(42);
				graph[x].ArcSet.add(43);
				graph[x].ArcSet.add(44);
				graph[x].ArcSet.add(45);
				break;
				
			case 17:
				//Freedom Park
				graph[x].SetXY(338, 187);
				graph[x].ArcSet.add(13);
				graph[x].ArcSet.add(14);
				graph[x].ArcSet.add(15);
				graph[x].ArcSet.add(19);
				graph[x].ArcSet.add(18);
				graph[x].ArcSet.add(20);
				graph[x].ArcSet.add(16);
				graph[x].ArcSet.add(30);
				graph[x].ArcSet.add(34);
				graph[x].ArcSet.add(31);
				graph[x].ArcSet.add(32);
				graph[x].ArcSet.add(33);
				graph[x].ArcSet.add(35);
				graph[x].ArcSet.add(37);
				graph[x].ArcSet.add(36);
				graph[x].ArcSet.add(12);
				graph[x].ArcSet.add(40);
				graph[x].ArcSet.add(39);
				graph[x].ArcSet.add(42);
				graph[x].ArcSet.add(38);
				graph[x].ArcSet.add(41);
				graph[x].ArcSet.add(43);
				graph[x].ArcSet.add(44);
				graph[x].ArcSet.add(45);
				break;
				
			case 18:
				//Gymnasium and Sports Center
				graph[x].SetXY(454, 40);
				graph[x].ArcSet.add(15);
				graph[x].ArcSet.add(19);
				graph[x].ArcSet.add(20);
				graph[x].ArcSet.add(23);
				graph[x].ArcSet.add(24);
				graph[x].ArcSet.add(27);
				graph[x].ArcSet.add(28);
				graph[x].ArcSet.add(16);
				graph[x].ArcSet.add(17);
				graph[x].ArcSet.add(34);
				graph[x].ArcSet.add(11);
				graph[x].ArcSet.add(29);
				graph[x].ArcSet.add(30);
				graph[x].ArcSet.add(31);
				graph[x].ArcSet.add(33);
				graph[x].ArcSet.add(32);
				graph[x].ArcSet.add(12);
				graph[x].ArcSet.add(16);
				graph[x].ArcSet.add(40);
				graph[x].ArcSet.add(39);
				graph[x].ArcSet.add(38);
				graph[x].ArcSet.add(41);
				graph[x].ArcSet.add(42);
				graph[x].ArcSet.add(43);
				graph[x].ArcSet.add(44);
				graph[x].ArcSet.add(45);
				graph[x].ArcSet.add(37);
				
				break;
				
			case 19:
				//Outdoor Basketball and VolleyBall Court
				graph[x].SetXY(400, 100);
				graph[x].ArcSet.add(13);
				graph[x].ArcSet.add(14);
				graph[x].ArcSet.add(15);
				graph[x].ArcSet.add(18);
				graph[x].ArcSet.add(20);
				graph[x].ArcSet.add(16);
				graph[x].ArcSet.add(21);
				graph[x].ArcSet.add(28);
				graph[x].ArcSet.add(29);
				graph[x].ArcSet.add(30);
				graph[x].ArcSet.add(31);
				graph[x].ArcSet.add(17);
				graph[x].ArcSet.add(34);
				graph[x].ArcSet.add(36);
				graph[x].ArcSet.add(40);
				graph[x].ArcSet.add(39);
				graph[x].ArcSet.add(11);
				graph[x].ArcSet.add(41);
				graph[x].ArcSet.add(42);
				graph[x].ArcSet.add(43);
				graph[x].ArcSet.add(44);
				graph[x].ArcSet.add(38);
				graph[x].ArcSet.add(12);
				graph[x].ArcSet.add(10);
				
				break;
				
			case 20:
				//Tennis Court
				graph[x].SetXY(460, 98);
				graph[x].ArcSet.add(13);
				graph[x].ArcSet.add(15);
				graph[x].ArcSet.add(18);
				graph[x].ArcSet.add(19);
				graph[x].ArcSet.add(23);
				graph[x].ArcSet.add(21);
				graph[x].ArcSet.add(24);
				graph[x].ArcSet.add(27);
				graph[x].ArcSet.add(28);
				graph[x].ArcSet.add(29);
				graph[x].ArcSet.add(32);
				graph[x].ArcSet.add(33);
				graph[x].ArcSet.add(30);
				graph[x].ArcSet.add(17);
				graph[x].ArcSet.add(16);
				graph[x].ArcSet.add(11);
				graph[x].ArcSet.add(12);
				graph[x].ArcSet.add(41);
				graph[x].ArcSet.add(40);
				
				break;
				
			case 21:
				//Covered Walkaway
				graph[x].SetXY(495, 148);
				graph[x].ArcSet.add(20);
				graph[x].ArcSet.add(21);
				graph[x].ArcSet.add(19);
				graph[x].ArcSet.add(13);
				graph[x].ArcSet.add(15);
				graph[x].ArcSet.add(23);
				graph[x].ArcSet.add(24);
				graph[x].ArcSet.add(27);
				graph[x].ArcSet.add(28);
				graph[x].ArcSet.add(26);
				graph[x].ArcSet.add(32);
				graph[x].ArcSet.add(33);
				graph[x].ArcSet.add(29);
				graph[x].ArcSet.add(30);
				graph[x].ArcSet.add(16);
				graph[x].ArcSet.add(11);
				break;
				
			case 22:
				//Anonas Street
				graph[x].SetXY(343, 517);
				graph[x].ArcSet.add(25);
				graph[x].ArcSet.add(26);
				graph[x].ArcSet.add(27);
				graph[x].ArcSet.add(24);
				break;
				
			case 23:
				//Visitor Information Center
				graph[x].SetXY(553, 62);
				graph[x].ArcSet.add(18);
				graph[x].ArcSet.add(20);
				graph[x].ArcSet.add(21);
				graph[x].ArcSet.add(28);
				graph[x].ArcSet.add(24);
				graph[x].ArcSet.add(27);
				graph[x].ArcSet.add(28);
				graph[x].ArcSet.add(33);
				graph[x].ArcSet.add(32);
				graph[x].ArcSet.add(29);
				graph[x].ArcSet.add(30);
				graph[x].ArcSet.add(16);
				graph[x].ArcSet.add(11);
				graph[x].ArcSet.add(12);
				break;
				
			case 24:
				//Pylon
				graph[x].SetXY(543, 134);
				graph[x].ArcSet.add(22);
				graph[x].ArcSet.add(25);
				graph[x].ArcSet.add(26);
				graph[x].ArcSet.add(27);
				graph[x].ArcSet.add(28);
				graph[x].ArcSet.add(21);
				graph[x].ArcSet.add(23);
				graph[x].ArcSet.add(20);
				graph[x].ArcSet.add(29);
				graph[x].ArcSet.add(16);
				
				break;
			
			case 25:
				//RailRoad Track
				graph[x].SetXY(584, 97);
				graph[x].ArcSet.add(22);
				graph[x].ArcSet.add(24);
				graph[x].ArcSet.add(26);
				graph[x].ArcSet.add(27);
				graph[x].ArcSet.add(28);
				break;
				
			case 26:
				//Teresa Street
				graph[x].SetXY(598, 140);
				graph[x].ArcSet.add(22);
				graph[x].ArcSet.add(25);
				graph[x].ArcSet.add(24);
				graph[x].ArcSet.add(27);
				graph[x].ArcSet.add(28);
				graph[x].ArcSet.add(16);
				graph[x].ArcSet.add(21);
				graph[x].ArcSet.add(23);
				graph[x].ArcSet.add(29);
				graph[x].ArcSet.add(21);
				break;
				
			case 27:
				//Main Gate Mural Bass Sculpture
				graph[x].SetXY(543, 148);
				graph[x].ArcSet.add(22);
				graph[x].ArcSet.add(25);
				graph[x].ArcSet.add(26);
				graph[x].ArcSet.add(24);
				graph[x].ArcSet.add(28);
				graph[x].ArcSet.add(21);
				graph[x].ArcSet.add(23);
				graph[x].ArcSet.add(20);
				graph[x].ArcSet.add(19);
				graph[x].ArcSet.add(13);
				graph[x].ArcSet.add(18);
				graph[x].ArcSet.add(19);
				graph[x].ArcSet.add(16);
				graph[x].ArcSet.add(11);
				graph[x].ArcSet.add(32);
				graph[x].ArcSet.add(33);
				graph[x].ArcSet.add(31);
				graph[x].ArcSet.add(37);
				graph[x].ArcSet.add(35);
				break;
				
			case 28:
				//Guard House
				graph[x].SetXY(538, 161);
				graph[x].ArcSet.add(22);
				graph[x].ArcSet.add(25);
				graph[x].ArcSet.add(26);
				graph[x].ArcSet.add(24);
				graph[x].ArcSet.add(27);
				graph[x].ArcSet.add(21);
				graph[x].ArcSet.add(20);
				graph[x].ArcSet.add(18);
				graph[x].ArcSet.add(19);
				graph[x].ArcSet.add(13);
				graph[x].ArcSet.add(23);
				graph[x].ArcSet.add(29);
				graph[x].ArcSet.add(32);
				graph[x].ArcSet.add(33);
				graph[x].ArcSet.add(31);
				graph[x].ArcSet.add(35);
				graph[x].ArcSet.add(37);
				graph[x].ArcSet.add(16);
				graph[x].ArcSet.add(11);
				graph[x].ArcSet.add(13);
				graph[x].ArcSet.add(15);
				break;
				
			case 29:
				//Gazebo
				graph[x].SetXY(415, 158);
				graph[x].ArcSet.add(20);
				graph[x].ArcSet.add(19);
				graph[x].ArcSet.add(23);
				graph[x].ArcSet.add(22);
				graph[x].ArcSet.add(24);
				graph[x].ArcSet.add(27);
				graph[x].ArcSet.add(26);
				graph[x].ArcSet.add(28);
				graph[x].ArcSet.add(21);
				graph[x].ArcSet.add(18);
				graph[x].ArcSet.add(30);
				graph[x].ArcSet.add(16);
				graph[x].ArcSet.add(10);
				graph[x].ArcSet.add(13);
				graph[x].ArcSet.add(14);
				graph[x].ArcSet.add(15);
				graph[x].ArcSet.add(18);
				graph[x].ArcSet.add(21);
				graph[x].ArcSet.add(11);
				break;
				
			case 30:
				//Apolinario Mabini Shrine
				graph[x].SetXY(386, 176);
				graph[x].ArcSet.add(29);
				graph[x].ArcSet.add(17);
				graph[x].ArcSet.add(34);
				graph[x].ArcSet.add(35);
				graph[x].ArcSet.add(37);
				graph[x].ArcSet.add(38);
				graph[x].ArcSet.add(16);
				graph[x].ArcSet.add(11);
				graph[x].ArcSet.add(19);
				graph[x].ArcSet.add(20);
				graph[x].ArcSet.add(18);
				graph[x].ArcSet.add(15);
				graph[x].ArcSet.add(19);
				graph[x].ArcSet.add(14);
				graph[x].ArcSet.add(13);
				graph[x].ArcSet.add(10);
				graph[x].ArcSet.add(12);
				graph[x].ArcSet.add(36);
				graph[x].ArcSet.add(40);
				graph[x].ArcSet.add(41);
				graph[x].ArcSet.add(39);
				graph[x].ArcSet.add(42);
				graph[x].ArcSet.add(43);
				graph[x].ArcSet.add(44);
				graph[x].ArcSet.add(45);
				graph[x].ArcSet.add(6);
				break;
			
			case 31:
				//Grandstand
				graph[x].SetXY(411, 220);
				graph[x].ArcSet.add(32);
				graph[x].ArcSet.add(33);
				graph[x].ArcSet.add(28);
				graph[x].ArcSet.add(21);
				graph[x].ArcSet.add(24);
				graph[x].ArcSet.add(27);
				graph[x].ArcSet.add(23);
				graph[x].ArcSet.add(25);
				graph[x].ArcSet.add(31);
				graph[x].ArcSet.add(37);
				graph[x].ArcSet.add(35);
				break;
				
			case 32:
				//Track and Football Oval
				graph[x].SetXY(466, 258);
				graph[x].ArcSet.add(33);
				graph[x].ArcSet.add(28);
				graph[x].ArcSet.add(27);
				graph[x].ArcSet.add(21);
				graph[x].ArcSet.add(24);
				graph[x].ArcSet.add(25);
				graph[x].ArcSet.add(23);
				graph[x].ArcSet.add(31);
				graph[x].ArcSet.add(37);
				graph[x].ArcSet.add(35);
				graph[x].ArcSet.add(38);
				graph[x].ArcSet.add(42);
				graph[x].ArcSet.add(43);
				graph[x].ArcSet.add(44);
				graph[x].ArcSet.add(45);
				break;
				
			case 33:
				//Community Building(Gabriela Silang)
				graph[x].SetXY(521, 299);
				graph[x].ArcSet.add(21);
				graph[x].ArcSet.add(28);
				graph[x].ArcSet.add(27);
				graph[x].ArcSet.add(24);
				graph[x].ArcSet.add(23);
				graph[x].ArcSet.add(25);
				graph[x].ArcSet.add(20);
				graph[x].ArcSet.add(18);
				graph[x].ArcSet.add(32);
				graph[x].ArcSet.add(31);
				graph[x].ArcSet.add(35);
				graph[x].ArcSet.add(37);
				graph[x].ArcSet.add(38);
				graph[x].ArcSet.add(43);
				graph[x].ArcSet.add(44);
				graph[x].ArcSet.add(42);
				graph[x].ArcSet.add(39);
				break;
				
			case 34:
				//Flag Pole
				graph[x].SetXY(335, 202);
				graph[x].ArcSet.add(13);
				graph[x].ArcSet.add(14);
				graph[x].ArcSet.add(15);
				graph[x].ArcSet.add(19);
				graph[x].ArcSet.add(18);
				graph[x].ArcSet.add(16);
				graph[x].ArcSet.add(30);
				graph[x].ArcSet.add(34);
				graph[x].ArcSet.add(31);
				graph[x].ArcSet.add(32);
				graph[x].ArcSet.add(33);
				graph[x].ArcSet.add(35);
				graph[x].ArcSet.add(37);
				graph[x].ArcSet.add(36);
				graph[x].ArcSet.add(12);
				graph[x].ArcSet.add(40);
				graph[x].ArcSet.add(39);
				graph[x].ArcSet.add(42);
				graph[x].ArcSet.add(38);
				graph[x].ArcSet.add(41);
				graph[x].ArcSet.add(43);
				graph[x].ArcSet.add(44);
				graph[x].ArcSet.add(45);
				break;
				
			case 35:
				//Interfaith Chapel
				graph[x].SetXY(316, 297);
				graph[x].ArcSet.add(31);
				graph[x].ArcSet.add(32);
				graph[x].ArcSet.add(33);
				graph[x].ArcSet.add(37);
				graph[x].ArcSet.add(21);
				graph[x].ArcSet.add(23);
				graph[x].ArcSet.add(24);
				graph[x].ArcSet.add(27);
				graph[x].ArcSet.add(25);
				graph[x].ArcSet.add(28);
				graph[x].ArcSet.add(45);
				graph[x].ArcSet.add(44);
				graph[x].ArcSet.add(43);
				graph[x].ArcSet.add(42);
				graph[x].ArcSet.add(38);
				graph[x].ArcSet.add(39);
				graph[x].ArcSet.add(40);
				graph[x].ArcSet.add(36);
				graph[x].ArcSet.add(34);
				graph[x].ArcSet.add(17);
				graph[x].ArcSet.add(13);
				graph[x].ArcSet.add(14);
				graph[x].ArcSet.add(15);
				graph[x].ArcSet.add(16);
				graph[x].ArcSet.add(30);
				graph[x].ArcSet.add(41);
				graph[x].ArcSet.add(12);
				graph[x].ArcSet.add(6);
				graph[x].ArcSet.add(5);
				graph[x].ArcSet.add(4);
				graph[x].ArcSet.add(11);
				graph[x].ArcSet.add(12);
				graph[x].ArcSet.add(3);

				break;
				
			case 36:
				//North Wing
				graph[x].SetXY(289, 229);
				graph[x].ArcSet.add(12);
				graph[x].ArcSet.add(40);
				graph[x].ArcSet.add(39);
				graph[x].ArcSet.add(41);
				graph[x].ArcSet.add(38);
				graph[x].ArcSet.add(42);
				graph[x].ArcSet.add(35);
				graph[x].ArcSet.add(17);
				graph[x].ArcSet.add(34);
				graph[x].ArcSet.add(37);
				graph[x].ArcSet.add(45);
				graph[x].ArcSet.add(43);
				graph[x].ArcSet.add(44);
				graph[x].ArcSet.add(47);
				graph[x].ArcSet.add(6);
				graph[x].ArcSet.add(4);
				graph[x].ArcSet.add(5);
				graph[x].ArcSet.add(3);
				graph[x].ArcSet.add(11);
				graph[x].ArcSet.add(15);
				graph[x].ArcSet.add(16);
				graph[x].ArcSet.add(19);
				graph[x].ArcSet.add(18);

				break;
				
			case 37:
				//Nutrition and Food Science Building
				graph[x].SetXY(314, 357);
				graph[x].ArcSet.add(45);
				graph[x].ArcSet.add(44);
				graph[x].ArcSet.add(43);
				graph[x].ArcSet.add(47);
				graph[x].ArcSet.add(6);
				graph[x].ArcSet.add(5);
				graph[x].ArcSet.add(4);
				graph[x].ArcSet.add(42);
				graph[x].ArcSet.add(41);
				graph[x].ArcSet.add(40);
				graph[x].ArcSet.add(39);
				graph[x].ArcSet.add(36);
				graph[x].ArcSet.add(38);
				graph[x].ArcSet.add(35);
				graph[x].ArcSet.add(17);
				graph[x].ArcSet.add(14);
				graph[x].ArcSet.add(13);
				graph[x].ArcSet.add(14);
				graph[x].ArcSet.add(15);
				graph[x].ArcSet.add(16);
				graph[x].ArcSet.add(31);
				graph[x].ArcSet.add(32);
				graph[x].ArcSet.add(33);
				graph[x].ArcSet.add(21);
				graph[x].ArcSet.add(23);
				graph[x].ArcSet.add(24);
				graph[x].ArcSet.add(27);
				graph[x].ArcSet.add(28);
				graph[x].ArcSet.add(25);
				
				break;
				
			case 38:
				//East Wing
				graph[x].SetXY(242, 306);
				graph[x].ArcSet.add(45);
				graph[x].ArcSet.add(44);
				graph[x].ArcSet.add(43);
				graph[x].ArcSet.add(42);
				graph[x].ArcSet.add(41);
				graph[x].ArcSet.add(39);
				graph[x].ArcSet.add(40);
				graph[x].ArcSet.add(36);
				graph[x].ArcSet.add(34);
				graph[x].ArcSet.add(17);
				graph[x].ArcSet.add(35);
				graph[x].ArcSet.add(37);
				graph[x].ArcSet.add(32);
				graph[x].ArcSet.add(33);
				graph[x].ArcSet.add(6);
				graph[x].ArcSet.add(5);
				graph[x].ArcSet.add(4);
				graph[x].ArcSet.add(9);
				graph[x].ArcSet.add(8);
				graph[x].ArcSet.add(7);
				graph[x].ArcSet.add(16);
				graph[x].ArcSet.add(15);
				graph[x].ArcSet.add(19);
				graph[x].ArcSet.add(18);
				
				break;
				
			case 39:
				//Dome
				graph[x].SetXY(241, 256);
				graph[x].ArcSet.add(32);
				graph[x].ArcSet.add(33);
				graph[x].ArcSet.add(35);
				graph[x].ArcSet.add(37);
				graph[x].ArcSet.add(38);
				graph[x].ArcSet.add(40);
				graph[x].ArcSet.add(36);
				graph[x].ArcSet.add(42);
				graph[x].ArcSet.add(41);
				graph[x].ArcSet.add(45);
				graph[x].ArcSet.add(44);
				graph[x].ArcSet.add(43);
				graph[x].ArcSet.add(6);
				graph[x].ArcSet.add(5);
				graph[x].ArcSet.add(4);
				graph[x].ArcSet.add(12);
				graph[x].ArcSet.add(17);
				graph[x].ArcSet.add(34);
				graph[x].ArcSet.add(16);
				graph[x].ArcSet.add(19);
				graph[x].ArcSet.add(18);
				
				break;
				
			case 40:
				//Main Building
				graph[x].SetXY(239, 239);
				graph[x].ArcSet.add(32);
				graph[x].ArcSet.add(33);
				graph[x].ArcSet.add(35);
				graph[x].ArcSet.add(37);
				graph[x].ArcSet.add(38);
				graph[x].ArcSet.add(39);
				graph[x].ArcSet.add(36);
				graph[x].ArcSet.add(42);
				graph[x].ArcSet.add(41);
				graph[x].ArcSet.add(45);
				graph[x].ArcSet.add(44);
				graph[x].ArcSet.add(43);
				graph[x].ArcSet.add(6);
				graph[x].ArcSet.add(5);
				graph[x].ArcSet.add(4);
				graph[x].ArcSet.add(12);
				graph[x].ArcSet.add(17);
				graph[x].ArcSet.add(34);
				graph[x].ArcSet.add(16);
				graph[x].ArcSet.add(19);
				graph[x].ArcSet.add(18);
				
				break;
				
			case 41:
				//West
				graph[x].SetXY(195, 230);
				graph[x].ArcSet.add(6);
				graph[x].ArcSet.add(5);
				graph[x].ArcSet.add(4);
				graph[x].ArcSet.add(12);
				graph[x].ArcSet.add(11);
				graph[x].ArcSet.add(7);
				graph[x].ArcSet.add(8);
				graph[x].ArcSet.add(9);
				graph[x].ArcSet.add(3);
				graph[x].ArcSet.add(40);
				graph[x].ArcSet.add(39);
				graph[x].ArcSet.add(36);
				graph[x].ArcSet.add(38);
				graph[x].ArcSet.add(35);
				graph[x].ArcSet.add(42);
				graph[x].ArcSet.add(43);
				graph[x].ArcSet.add(44);
				graph[x].ArcSet.add(37);
				graph[x].ArcSet.add(35);
				graph[x].ArcSet.add(32);
				graph[x].ArcSet.add(33);
				break;
			
			case 42:
				//South
				graph[x].SetXY(182, 289);
				graph[x].ArcSet.add(3);
				graph[x].ArcSet.add(43);
				graph[x].ArcSet.add(44);
				graph[x].ArcSet.add(6);
				graph[x].ArcSet.add(5);
				graph[x].ArcSet.add(4);
				graph[x].ArcSet.add(38);
				graph[x].ArcSet.add(41);
				graph[x].ArcSet.add(40);
				graph[x].ArcSet.add(39);
				graph[x].ArcSet.add(36);
				graph[x].ArcSet.add(17);
				graph[x].ArcSet.add(34);
				graph[x].ArcSet.add(35);
				graph[x].ArcSet.add(37);
				graph[x].ArcSet.add(32);
				graph[x].ArcSet.add(12);
				graph[x].ArcSet.add(11);
				graph[x].ArcSet.add(17);
				graph[x].ArcSet.add(34);
				graph[x].ArcSet.add(16);
				graph[x].ArcSet.add(19);
				graph[x].ArcSet.add(18);
				graph[x].ArcSet.add(7);
				graph[x].ArcSet.add(8);
				graph[x].ArcSet.add(9);
				break;

			case 43:
				//Generator Facility
				graph[x].SetXY(162, 330);
				graph[x].ArcSet.add(3);
				graph[x].ArcSet.add(42);
				graph[x].ArcSet.add(44);
				graph[x].ArcSet.add(6);
				graph[x].ArcSet.add(5);
				graph[x].ArcSet.add(4);
				graph[x].ArcSet.add(38);
				graph[x].ArcSet.add(41);
				graph[x].ArcSet.add(40);
				graph[x].ArcSet.add(39);
				graph[x].ArcSet.add(36);
				graph[x].ArcSet.add(17);
				graph[x].ArcSet.add(34);
				graph[x].ArcSet.add(35);
				graph[x].ArcSet.add(37);
				graph[x].ArcSet.add(32);
				graph[x].ArcSet.add(12);
				graph[x].ArcSet.add(11);
				graph[x].ArcSet.add(17);
				graph[x].ArcSet.add(34);
				graph[x].ArcSet.add(16);
				graph[x].ArcSet.add(19);
				graph[x].ArcSet.add(18);
				graph[x].ArcSet.add(7);
				graph[x].ArcSet.add(8);
				graph[x].ArcSet.add(9);
				break;
			
			case 44:
				//PUP Sta.Mesa Ferry Station
				graph[x].SetXY(168, 348);
				graph[x].ArcSet.add(3);
				graph[x].ArcSet.add(43);
				graph[x].ArcSet.add(42);
				graph[x].ArcSet.add(6);
				graph[x].ArcSet.add(5);
				graph[x].ArcSet.add(4);
				graph[x].ArcSet.add(38);
				graph[x].ArcSet.add(41);
				graph[x].ArcSet.add(40);
				graph[x].ArcSet.add(39);
				graph[x].ArcSet.add(36);
				graph[x].ArcSet.add(17);
				graph[x].ArcSet.add(34);
				graph[x].ArcSet.add(35);
				graph[x].ArcSet.add(37);
				graph[x].ArcSet.add(32);
				graph[x].ArcSet.add(12);
				graph[x].ArcSet.add(11);
				graph[x].ArcSet.add(17);
				graph[x].ArcSet.add(34);
				graph[x].ArcSet.add(16);
				graph[x].ArcSet.add(19);
				graph[x].ArcSet.add(18);
				graph[x].ArcSet.add(7);
				graph[x].ArcSet.add(8);
				graph[x].ArcSet.add(9);
				
				break;
			
			case 45:
				//Campus Development and Maintenance building
				graph[x].SetXY(222, 359);
				graph[x].ArcSet.add(3);
				graph[x].ArcSet.add(43);
				graph[x].ArcSet.add(44);
				graph[x].ArcSet.add(6);
				graph[x].ArcSet.add(5);
				graph[x].ArcSet.add(4);
				graph[x].ArcSet.add(38);
				graph[x].ArcSet.add(41);
				graph[x].ArcSet.add(40);
				graph[x].ArcSet.add(39);
				graph[x].ArcSet.add(36);
				graph[x].ArcSet.add(17);
				graph[x].ArcSet.add(34);
				graph[x].ArcSet.add(35);
				graph[x].ArcSet.add(37);
				graph[x].ArcSet.add(32);
				graph[x].ArcSet.add(12);
				graph[x].ArcSet.add(11);
				graph[x].ArcSet.add(17);
				graph[x].ArcSet.add(34);
				graph[x].ArcSet.add(16);
				graph[x].ArcSet.add(19);
				graph[x].ArcSet.add(18);
				graph[x].ArcSet.add(7);
				graph[x].ArcSet.add(8);
				graph[x].ArcSet.add(9);
				graph[x].ArcSet.add(31);
				graph[x].ArcSet.add(28);
				graph[x].ArcSet.add(21);
				graph[x].ArcSet.add(27);
				graph[x].ArcSet.add(24);
				graph[x].ArcSet.add(25);
				
				break;
			
			case 46:
				//Linear Park
				graph[x].SetXY(222, 359);
				graph[x].ArcSet.add(6);
				graph[x].ArcSet.add(4);
				graph[x].ArcSet.add(12);
				graph[x].ArcSet.add(11);
				graph[x].ArcSet.add(7);
				graph[x].ArcSet.add(8);
				graph[x].ArcSet.add(9);
				graph[x].ArcSet.add(3);
				graph[x].ArcSet.add(40);
				graph[x].ArcSet.add(39);
				graph[x].ArcSet.add(36);
				graph[x].ArcSet.add(38);
				graph[x].ArcSet.add(35);
				graph[x].ArcSet.add(42);
				graph[x].ArcSet.add(43);
				graph[x].ArcSet.add(44);
				graph[x].ArcSet.add(37);
				graph[x].ArcSet.add(35);
				graph[x].ArcSet.add(32);
				graph[x].ArcSet.add(33);
				graph[x].ArcSet.add(3);
				graph[x].ArcSet.add(1);
				graph[x].ArcSet.add(0);
				
			case 47:
				//Dummy Node
				graph[x].SetXY(113,1);
				graph[x].ArcSet.add(0);
				graph[x].ArcSet.add(1);
				graph[x].ArcSet.add(48);
				graph[x].ArcSet.add(49);
				
			
			case 48:
				//Dummy Node
				graph[x].SetXY(164,20);
				graph[x].ArcSet.add(47);
				graph[x].ArcSet.add(7);
				graph[x].ArcSet.add(8);
				graph[x].ArcSet.add(9);
				graph[x].ArcSet.add(50);
				
			case 49:
				//Dummy Node
				graph[x].SetXY(88,34);
				graph[x].ArcSet.add(47);
				graph[x].ArcSet.add(0);
				graph[x].ArcSet.add(1);
				graph[x].ArcSet.add(2);
				graph[x].ArcSet.add(3);
			
			case 50:
				//Dummy Node
				graph[x].SetXY(190,83);
				graph[x].ArcSet.add(48);
				graph[x].ArcSet.add(9);
				graph[x].ArcSet.add(2);
				graph[x].ArcSet.add(10);
				graph[x].ArcSet.add(51);
				
			
			case 51:
				//Dummy Node
				graph[x].SetXY(203,105);
				graph[x].ArcSet.add(50);
				graph[x].ArcSet.add(10);
				graph[x].ArcSet.add(4);
				graph[x].ArcSet.add(2);
				graph[x].ArcSet.add(52);
				graph[x].ArcSet.add(53);
			
			case 52:
				//Dummy Node
				graph[x].SetXY(211,148);
				graph[x].ArcSet.add(51);
				graph[x].ArcSet.add(11);
				graph[x].ArcSet.add(12);
				graph[x].ArcSet.add(54);
				
			case 53:
				//Dummy Node
				graph[x].SetXY(177,161);
				graph[x].ArcSet.add(51);
				graph[x].ArcSet.add(54);
				graph[x].ArcSet.add(55);
				graph[x].ArcSet.add(4);
				graph[x].ArcSet.add(5);
				graph[x].ArcSet.add(6);
			
			case 54:
				//Dummy Node
				graph[x].SetXY(208,177);
				graph[x].ArcSet.add(52);
				graph[x].ArcSet.add(53);
				graph[x].ArcSet.add(11);
				graph[x].ArcSet.add(56);
				
			case 55:
				//Dummy Node
				graph[x].SetXY(164,185);
				graph[x].ArcSet.add(53);
				graph[x].ArcSet.add(5);
				graph[x].ArcSet.add(6);
				graph[x].ArcSet.add(56);
				graph[x].ArcSet.add(58);
				graph[x].ArcSet.add(41);
				
			case 56:
				//Dummy Node
				graph[x].SetXY(202,201);
				graph[x].ArcSet.add(54);
				graph[x].ArcSet.add(55);
				graph[x].ArcSet.add(41);
				graph[x].ArcSet.add(57);
			
			case 57:
				//Dummy Node
				graph[x].SetXY(239,222);
				graph[x].ArcSet.add(56);
				graph[x].ArcSet.add(41);
				graph[x].ArcSet.add(40);
				graph[x].ArcSet.add(36);
				graph[x].ArcSet.add(67);
				
			case 58:
				//Dummy Node
				graph[x].SetXY(132,242);
				graph[x].ArcSet.add(55);
				graph[x].ArcSet.add(42);
				graph[x].ArcSet.add(3);
				graph[x].ArcSet.add(59);
				graph[x].ArcSet.add(43);
				
			case 59:
				//Dummy Node
				graph[x].SetXY(193,353);
				graph[x].ArcSet.add(58);
				graph[x].ArcSet.add(42);
				graph[x].ArcSet.add(43);
				graph[x].ArcSet.add(44);
				graph[x].ArcSet.add(45);
				graph[x].ArcSet.add(38);
				graph[x].ArcSet.add(60);
			
			case 60:
				//Dummy Node
				graph[x].SetXY(261,348);
				graph[x].ArcSet.add(59);
				graph[x].ArcSet.add(61);
				graph[x].ArcSet.add(37);
				graph[x].ArcSet.add(38);
			
			case 61:
				//Dummy Node
				graph[x].SetXY(290,340);
				graph[x].ArcSet.add(60);
				graph[x].ArcSet.add(37);
				graph[x].ArcSet.add(62);
				graph[x].ArcSet.add(35);
				graph[x].ArcSet.add(63);
			
			case 62:
				//Dummy Node
				graph[x].SetXY(342,338);
				graph[x].ArcSet.add(61);
				graph[x].ArcSet.add(35);
				graph[x].ArcSet.add(37);
				graph[x].ArcSet.add(64);
				
			case 63:
				//Dummy Node
				graph[x].SetXY(273,308);
				graph[x].ArcSet.add(61);
				graph[x].ArcSet.add(65);
				graph[x].ArcSet.add(38);
				graph[x].ArcSet.add(35);
			
			case 64:
				//Dummy Node
				graph[x].SetXY(361,304);
				graph[x].ArcSet.add(62);
				graph[x].ArcSet.add(35);
				graph[x].ArcSet.add(66);
				graph[x].ArcSet.add(33);
				graph[x].ArcSet.add(31);
				graph[x].ArcSet.add(32);
				
			case 65:
				//Dummy Node
				graph[x].SetXY(286,264);
				graph[x].ArcSet.add(63);
				graph[x].ArcSet.add(36);
				graph[x].ArcSet.add(39);
				graph[x].ArcSet.add(40);
				graph[x].ArcSet.add(38);
				graph[x].ArcSet.add(67);
				graph[x].ArcSet.add(35);
				
			case 66:
				//Dummy Node
				graph[x].SetXY(358,265);
				graph[x].ArcSet.add(64);
				graph[x].ArcSet.add(35);
				graph[x].ArcSet.add(67);
				graph[x].ArcSet.add(31);
				graph[x].ArcSet.add(32);
				graph[x].ArcSet.add(65);
				
			case 67:
				//Dummy Node
				graph[x].SetXY(316,247);
				graph[x].ArcSet.add(65);
				graph[x].ArcSet.add(35);
				graph[x].ArcSet.add(66);
				graph[x].ArcSet.add(36);
				graph[x].ArcSet.add(34);
				
			case 68:
				//Dummy Node
				graph[x].SetXY(298,191);
				graph[x].ArcSet.add(34);
				graph[x].ArcSet.add(36);
				graph[x].ArcSet.add(27);
				graph[x].ArcSet.add(69);
				graph[x].ArcSet.add(11);
				graph[x].ArcSet.add(12);
				graph[x].ArcSet.add(57);
				
			case 69:
				//Dummy Node
				graph[x].SetXY(337,160);
				graph[x].ArcSet.add(27);
				graph[x].ArcSet.add(68);
				graph[x].ArcSet.add(11);
				graph[x].ArcSet.add(73);
				graph[x].ArcSet.add(74);
				graph[x].ArcSet.add(72);
				graph[x].ArcSet.add(16);
				
			case 70:
				//Dummy Node
				graph[x].SetXY(413,185);
				graph[x].ArcSet.add(29);
				graph[x].ArcSet.add(30);
				graph[x].ArcSet.add(31);	
				graph[x].ArcSet.add(71);

			case 71:
				//Dummy Node
				graph[x].SetXY(468,153);
				graph[x].ArcSet.add(70);
				graph[x].ArcSet.add(29);
				graph[x].ArcSet.add(20);
				graph[x].ArcSet.add(80);
				graph[x].ArcSet.add(21);
				
			case 72:
				//Dummy Node
				graph[x].SetXY(379,145);
				graph[x].ArcSet.add(30);
				graph[x].ArcSet.add(69);
				graph[x].ArcSet.add(16);
				graph[x].ArcSet.add(73);
				graph[x].ArcSet.add(74);
				graph[x].ArcSet.add(19);
				graph[x].ArcSet.add(71);
				graph[x].ArcSet.add(29);
			
			case 73:
				//Dummy Node
				graph[x].SetXY(340,117);
				graph[x].ArcSet.add(16);
				graph[x].ArcSet.add(69);
				graph[x].ArcSet.add(11);
				graph[x].ArcSet.add(76);
				graph[x].ArcSet.add(75);
				graph[x].ArcSet.add(74);
				
			case 74:
				//Dummy Node
				graph[x].SetXY(352,113);
				graph[x].ArcSet.add(16);
				graph[x].ArcSet.add(73);
				graph[x].ArcSet.add(76);
				graph[x].ArcSet.add(75);
				graph[x].ArcSet.add(19);
				graph[x].ArcSet.add(71);
				graph[x].ArcSet.add(72);
				
			case 75:
				//Dummy Node
				graph[x].SetXY(342,105);
				graph[x].ArcSet.add(19);
				graph[x].ArcSet.add(73);
				graph[x].ArcSet.add(74);
				graph[x].ArcSet.add(76);
				graph[x].ArcSet.add(13);
				graph[x].ArcSet.add(14);
				graph[x].ArcSet.add(15);
				
			case 76:
				//Dummy Node
				graph[x].SetXY(316,100);
				graph[x].ArcSet.add(11);
				graph[x].ArcSet.add(77);
				graph[x].ArcSet.add(78);
				graph[x].ArcSet.add(13);
				graph[x].ArcSet.add(14);
				graph[x].ArcSet.add(75);
				graph[x].ArcSet.add(74);
				graph[x].ArcSet.add(73);
				
			case 77:
				//Dummy Node
				graph[x].SetXY(290,77);
				graph[x].ArcSet.add(76);
				graph[x].ArcSet.add(10);
				graph[x].ArcSet.add(78);
				graph[x].ArcSet.add(13);
				
			case 78:
				//Dummy Node
				graph[x].SetXY(293,58);
				graph[x].ArcSet.add(77);
				graph[x].ArcSet.add(10);
				graph[x].ArcSet.add(79);
				graph[x].ArcSet.add(13);

			case 79:
				//Dummy Node
				graph[x].SetXY(281,27);
				graph[x].ArcSet.add(13);
				graph[x].ArcSet.add(78);
				graph[x].ArcSet.add(10);
				
			case 80:
				//Dummy Node
				graph[x].SetXY(506,146);
				graph[x].ArcSet.add(21);
				graph[x].ArcSet.add(71);
				graph[x].ArcSet.add(23);
				graph[x].ArcSet.add(24);
				graph[x].ArcSet.add(27);
				graph[x].ArcSet.add(28);
				
			case 81:
				//Dummy Node
				graph[x].SetXY(494,77);
				graph[x].ArcSet.add(18);
				graph[x].ArcSet.add(20);
				graph[x].ArcSet.add(23);
				graph[x].ArcSet.add(24);
				
			case 82:
				//Dummy Node
				graph[x].SetXY(557,141);
				graph[x].ArcSet.add(27);
				graph[x].ArcSet.add(80);
				graph[x].ArcSet.add(24);
				graph[x].ArcSet.add(22);
				graph[x].ArcSet.add(25);
				graph[x].ArcSet.add(26);
		}
        }
        for(int x = 0;x < 42; x++){
            if(x == chStart.getSelectedIndex())graph[x].total = 0;
	}
        int s = 0;
        double tempDist = 0;
        int tempIndex = 0;
	do {					
	for (s = 0; graph[s].visited; s++);// s stands for smallest
				for (int x = s; x < 42; x++)
					if (!graph[x].visited && graph[x].total < graph[s].total)
						s = x;
				if (s == chEnd.getSelectedIndex())
					break;
				else
					for (ListNode util = graph[s].ArcSet.head(); util != null; util = util.next) {
						if (graph[util.data].visited)
							continue;
						tempDist = graph[s].total + Math.abs(Math.sqrt((Math.pow((graph[s].x-graph[util.data].x),2))+(Math.pow((graph[s].y-graph[util.data].y),2))));
						tempIndex = s;
						if (tempDist < graph[util.data].total) {
							graph[util.data].total = tempDist;
							graph[util.data].origin = tempIndex;
						}
					}
				graph[s].visited = true;												
			} while (true);
        Graphics g=this.imgMap.getGraphics();
        g.setColor(Color.YELLOW);
        for(int util=chEnd.getSelectedIndex();util!=chStart.getSelectedIndex();util=graph[util].origin){
            g.drawLine(graph[util].x,graph[util].y,graph[graph[util].origin].x,graph[graph[util].origin].y);
	}
        this.btnOk.setEnabled(false);
    }//GEN-LAST:event_btnOkActionPerformed

    private void imgMapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgMapMouseClicked
        JOptionPane.showMessageDialog(null,"X:"+evt.getX()+"\nY:"+evt.getY());
    }//GEN-LAST:event_imgMapMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Places.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Places.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Places.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Places.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Places().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBack;
    private javax.swing.JButton btnOk;
    private java.awt.Choice chEnd;
    private java.awt.Choice chStart;
    private javax.swing.JLabel imgMap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblEnd;
    private javax.swing.JLabel lblStart;
    // End of variables declaration//GEN-END:variables
}
